import re
from utils.parser import calculate_health_score

# Comprehensive glossary of medical terms with user-friendly explanations
MEDICAL_GLOSSARY = {
    "hba1c": {
        "full_name": "Glycated Hemoglobin (HbA1c)",
        "explanation": "HbA1c measures your average blood sugar levels over the past 2 to 3 months. Unlike standard daily glucose tests, it indicates long-term blood sugar control. A level below 5.7% is normal, 5.7% to 6.4% indicates prediabetes, and 6.5% or higher indicates diabetes.",
        "actions": "To lower HbA1c, focus on reducing refined carbs, exercising regularly, and managing weight."
    },
    "glucose": {
        "full_name": "Blood Glucose (Sugar)",
        "explanation": "Glucose is the main sugar found in your blood and is your body's primary source of energy. Fasting glucose is measured after not eating for 8+ hours (normal: 70-100 mg/dL). Postprandial glucose is measured 2 hours after a meal (normal: <140 mg/dL). High levels can indicate insulin resistance or diabetes.",
        "actions": "A healthy diet low in sugars, weight control, and active exercise help keep glucose in check."
    },
    "sugar": {
        "full_name": "Blood Glucose / Sugar",
        "explanation": "See Blood Glucose. High blood sugar occurs when your body doesn't produce enough insulin or cannot use it effectively, leading to energy spikes, fatigue, and potential long-term organ damage.",
        "actions": "Focus on high-fiber foods, stay hydrated, and exercise to help cells absorb glucose."
    },
    "hemoglobin": {
        "full_name": "Hemoglobin (Hb)",
        "explanation": "Hemoglobin is an iron-rich protein in red blood cells that carries oxygen from your lungs to the rest of your body. Low levels (anemia) cause tiredness, weakness, and pale skin. Normal ranges are typically 13.8 - 17.2 g/dL for men and 12.1 - 15.1 g/dL for women.",
        "actions": "Eat iron-rich foods (red meat, spinach, legumes) paired with Vitamin C to improve absorption."
    },
    "hb": {
        "full_name": "Hemoglobin",
        "explanation": "See Hemoglobin. It is the key protein in your red blood cells responsible for oxygen transport.",
        "actions": "Improve dietary iron and check for B12/folate levels if low."
    },
    "cholesterol": {
        "full_name": "Cholesterol (Lipid Profile)",
        "explanation": "Cholesterol is a waxy substance found in your blood. Your body needs it to build healthy cells, but high levels of LDL ('bad') cholesterol or total cholesterol can form plaques in your arteries, increasing heart disease and stroke risk.",
        "actions": "Reduce saturated fats, avoid trans fats, consume omega-3s, and run or jog regularly to raise HDL ('good') cholesterol."
    },
    "ldl": {
        "full_name": "LDL Cholesterol ('Bad' Cholesterol)",
        "explanation": "Low-Density Lipoprotein (LDL) carries cholesterol to your cells. Excess LDL accumulates on artery walls (plaque), leading to atherosclerosis ('clogging of arteries'). Levels should ideally be under 100 mg/dL.",
        "actions": "Increase soluble fiber (oats, beans), eat healthy fats (olive oil, avocados), and exercise."
    },
    "hdl": {
        "full_name": "HDL Cholesterol ('Good' Cholesterol)",
        "explanation": "High-Density Lipoprotein (HDL) acts as a scavenger, absorbing excess cholesterol and carrying it back to the liver to be flushed from the body. High levels (>40 mg/dL for men, >50 mg/dL for women) protect against cardiovascular diseases.",
        "actions": "Healthy fats, aerobic workouts, and avoiding smoking help elevate HDL."
    },
    "triglycerides": {
        "full_name": "Triglycerides",
        "explanation": "Triglycerides are the most common type of fat in your body, storing excess energy from your diet. Elevated triglycerides (>150 mg/dL) combined with high LDL increase the risk of heart attacks and pancreatitis.",
        "actions": "Reduce sugar, alcohol, and simple carbohydrates. Incorporate fish oils and engage in regular workouts."
    },
    "tsh": {
        "full_name": "Thyroid Stimulating Hormone (TSH)",
        "explanation": "TSH is produced by the pituitary gland to control your thyroid gland's hormone output. High TSH (>4.5 mIU/L) suggests an underactive thyroid (hypothyroidism), meaning your body is struggling to make enough thyroid hormone. Low TSH (<0.4 mIU/L) suggests an overactive thyroid (hyperthyroidism).",
        "actions": "Consult an endocrinologist. Hypothyroidism is often managed with synthetic thyroid hormone (Levothyroxine)."
    },
    "creatinine": {
        "full_name": "Serum Creatinine",
        "explanation": "Creatinine is a chemical waste product generated by muscle metabolism. Healthy kidneys filter creatinine from the blood and excrete it in urine. Elevated levels (>1.2 or 1.3 mg/dL) indicate that the kidneys may not be filtering waste effectively.",
        "actions": "Stay properly hydrated, avoid heavy creatine supplements, and limit high-protein diets under medical supervision."
    },
    "wbc": {
        "full_name": "White Blood Cell Count (WBC)",
        "explanation": "WBCs are key components of your immune system that fight infections. High WBC counts (>11,000 cells/mcL) usually point to an infection, inflammation, or physical stress. Low WBC counts (<4,000 cells/mcL) can indicate viral infections, bone marrow issues, or autoimmune conditions.",
        "actions": "If high, seek medical advice to identify any underlying infection or inflammatory source."
    },
    "rbc": {
        "full_name": "Red Blood Cell Count (RBC)",
        "explanation": "RBCs contain hemoglobin and are responsible for delivering oxygen to tissues. Low RBC counts lead to fatigue and anemia. High RBC counts can occur in response to low oxygen levels (e.g. high altitudes, smoking) or dehydration.",
        "actions": "Drink plenty of fluids. Check iron, vitamin B12, and folic acid levels."
    },
    "platelets": {
        "full_name": "Platelets (Thrombocytes)",
        "explanation": "Platelets are cell fragments that help your blood clot to stop bleeding. A low count (<150,000) causes easy bruising and prolonged bleeding. A high count (>450,000) can cause abnormal blood clots.",
        "actions": "Avoid self-medicating with blood-thinning painkillers (like aspirin) if platelets are low, and consult a doctor."
    },
    "bp": {
        "full_name": "Blood Pressure (BP)",
        "explanation": "Blood pressure is the force of blood pushing against artery walls. It is written as systolic/diastolic (e.g., 120/80 mmHg). High blood pressure (hypertension, >=130/80 mmHg) strains the heart and blood vessels, leading to cardiovascular risks.",
        "actions": "Reduce salt, stay active, manage stress, and limit alcohol consumption."
    },
    "blood pressure": {
        "full_name": "Blood Pressure (BP)",
        "explanation": "See Blood Pressure. High readings are often called 'the silent killer' because they rarely show obvious symptoms but increase risk of heart attack and stroke.",
        "actions": "Incorporate the DASH diet (high in vegetables/fruits, low in sodium) and exercise regularly."
    },
    "anemia": {
        "full_name": "Anemia",
        "explanation": "Anemia is a condition where your blood has fewer healthy red blood cells or less hemoglobin than normal. It often causes fatigue, weakness, pale skin, and shortness of breath.",
        "actions": "Eat iron-rich foods, take vitamin C with meals for better iron absorption, and consult a doctor for further testing if symptoms persist."
    },
    "diabetes": {
        "full_name": "Diabetes",
        "explanation": "Diabetes is a chronic condition where your body struggles to control blood sugar levels. It is often diagnosed by elevated fasting glucose, HbA1c, or postprandial glucose readings.",
        "actions": "Control carbohydrate intake, maintain a healthy weight, stay active, and follow your healthcare provider's recommendations."
    },
    "hypertension": {
        "full_name": "Hypertension (High Blood Pressure)",
        "explanation": "Hypertension means your blood pressure is consistently above the healthy range. It can damage the heart, kidneys, and blood vessels over time.",
        "actions": "Reduce alcohol and sodium intake, exercise regularly, manage stress, and monitor blood pressure often."
    },
    "thyroid": {
        "full_name": "Thyroid Function",
        "explanation": "The thyroid gland controls metabolism, energy levels, and hormone balance. Abnormal TSH values may indicate underactive or overactive thyroid function.",
        "actions": "Discuss abnormal thyroid tests with an endocrinologist and follow their treatment plan."
    },
    "kidney": {
        "full_name": "Kidney Function",
        "explanation": "Kidneys filter waste and maintain fluid, electrolyte, and blood pressure balance. High creatinine or abnormal kidney markers can indicate reduced kidney function.",
        "actions": "Stay hydrated, limit excessive protein intake, and get follow-up testing if kidney markers are elevated."
    }
}

DISCLAIMER = "\n\n*Disclaimer: I am an AI Health Assistant, not a medical professional. This information is for educational purposes only and should not replace clinical diagnosis, advice, or treatment from a qualified doctor.*"

def _normalize_query(query):
    return re.sub(r'[^a-z0-9 ]', ' ', query.lower())


def _find_glossary_matches(query_lower):
    normalized = _normalize_query(query_lower)
    return [term for term in MEDICAL_GLOSSARY if re.search(r'\b' + re.escape(term) + r'\b', normalized)]


def _get_report_context(term, biomarkers):
    if not biomarkers:
        return ""

    bio_name_map = {
        "hba1c": ["HbA1c"],
        "glucose": ["Fasting Glucose", "Postprandial Glucose"],
        "sugar": ["Fasting Glucose", "Postprandial Glucose"],
        "hemoglobin": ["Hemoglobin"],
        "hb": ["Hemoglobin"],
        "cholesterol": ["Total Cholesterol"],
        "ldl": ["LDL Cholesterol"],
        "hdl": ["HDL Cholesterol"],
        "triglycerides": ["Triglycerides"],
        "tsh": ["Thyroid TSH"],
        "creatinine": ["Creatinine"],
        "wbc": ["WBC"],
        "rbc": ["RBC"],
        "platelets": ["Platelets"],
        "bp": ["Systolic BP", "Diastolic BP"],
        "blood pressure": ["Systolic BP", "Diastolic BP"]
    }

    mapped = bio_name_map.get(term, [])
    if not mapped:
        return ""

    user_bios = [b for b in biomarkers if b["name"] in mapped]
    if not user_bios:
        return ""

    report_context = "\n\n**Your Current Levels:**\n"
    for ub in user_bios:
        status_emoji = "✅" if ub["status"] == "Normal" else "⚠️" if ub["status"] == "Borderline" else "🚨"
        report_context += f"- **{ub['name']}**: {ub['value']} {ub['unit']} ({status_emoji} {ub['status']}, reference range: {ub['reference_range']})\n"
    return report_context


def _is_general_medical_query(query_lower):
    general_keywords = [
        "what is", "explain", "normal range", "risk", "symptom", "sign", "cause",
        "treat", "treatment", "medicine", "medication", "diet", "exercise",
        "workout", "health score", "report", "lab", "doctor", "emergency", "urgent",
        "how to", "why", "when to", "help", "should i", "can i"
    ]
    return any(word in query_lower for word in general_keywords)


def _find_condition_matches(query_lower):
    condition_words = {
        "diabetes": ["diabetes", "blood sugar", "type 1", "type 2"],
        "anemia": ["anemia", "anemic", "hemoglobin low", "low hb"],
        "hypertension": ["hypertension", "high blood pressure", "bp high", "high bp"],
        "heart disease": ["heart disease", "cardiac", "heart attack", "chest pain", "angina"],
        "thyroid": ["thyroid", "tsh", "hypothyroidism", "hyperthyroidism"],
        "kidney": ["kidney", "renal", "creatinine"],
        "emergency": ["emergency", "urgent", "chest pain", "shortness of breath", "difficulty breathing", "faint", "collapse"]
    }
    for condition, terms in condition_words.items():
        if any(term in query_lower for term in terms):
            return condition
    return None


def _build_condition_response(query_lower, biomarkers, user_profile=None):
    condition = _find_condition_matches(query_lower)
    if not condition:
        return None

    if condition == "diabetes":
        return (
            "Diabetes is a chronic condition characterized by high blood sugar levels. "
            "It can be indicated by elevated fasting glucose, postprandial glucose, or HbA1c. "
            "Management includes a balanced diet, regular exercise, consistent carbohydrate intake, and monitoring your blood sugar regularly. "
            "If you notice increased thirst, frequent urination, fatigue, or blurry vision, please see a healthcare provider for evaluation."
            + DISCLAIMER
        )

    if condition == "anemia":
        return (
            "Anemia occurs when your blood has too few healthy red blood cells or hemoglobin. "
            "It can cause fatigue, weakness, pale skin, and shortness of breath. "
            "Common causes include iron deficiency, vitamin B12 or folate deficiency, and chronic illness. "
            "A diet rich in iron, vitamin C, and B vitamins can help, but please consult a doctor for proper diagnosis and treatment."
            + DISCLAIMER
        )

    if condition == "hypertension":
        return (
            "Hypertension, or high blood pressure, means your heart is pumping blood with too much force against your artery walls. "
            "It often has no symptoms, so regular monitoring is important. "
            "Lifestyle changes such as reducing salt, maintaining a healthy weight, staying active, and avoiding excessive alcohol can help lower blood pressure. "
            "Talk to your doctor if your readings stay consistently high."
            + DISCLAIMER
        )

    if condition == "heart disease":
        return (
            "Heart disease is a group of conditions that affect how well your heart functions and can include blocked arteries, heart failure, and irregular rhythms. "
            "Risk factors include high cholesterol, high blood pressure, diabetes, smoking, and family history. "
            "A heart-healthy diet, regular exercise, and managing stress are important, and any chest discomfort or shortness of breath should be evaluated immediately."
            + DISCLAIMER
        )

    if condition == "thyroid":
        return (
            "Thyroid function affects your metabolism, energy levels, and temperature regulation. "
            "Abnormal TSH may mean your thyroid is underactive or overactive. "
            "Symptoms can include fatigue, weight changes, and temperature sensitivity. "
            "Consult an endocrinologist if you have concerns or abnormal thyroid blood tests."
            + DISCLAIMER
        )

    if condition == "kidney":
        return (
            "Kidneys filter waste from your blood and balance fluid and electrolytes. "
            "High creatinine or abnormal renal markers can indicate reduced kidney function. "
            "Drink enough water, avoid excessive protein if advised by a doctor, and follow up with specialist testing if kidney function is uncertain."
            + DISCLAIMER
        )

    if condition == "emergency":
        return (
            "If you are experiencing severe symptoms such as chest pain, sudden shortness of breath, loss of consciousness, or sudden weakness, seek emergency medical care immediately. "
            "This assistant can provide general educational information, but it cannot replace urgent clinical evaluation."
            + DISCLAIMER
        )

    return None


def _build_general_response(query_lower, biomarkers=None):
    if "symptom" in query_lower or "sign" in query_lower or "cause" in query_lower:
        return (
            "Symptoms vary depending on the underlying condition. If you provide a specific symptom or lab finding, I can give a clearer explanation. "
            "Generally, persistent changes in energy, appetite, breathing, or pain should be evaluated by a healthcare provider."
            + DISCLAIMER
        )

    if "treatment" in query_lower or "treat" in query_lower or "medicine" in query_lower or "medication" in query_lower:
        return (
            "Treatment depends on the diagnosis and may include lifestyle changes, medications, or monitoring. "
            "For example, high blood pressure is often managed with diet, exercise, and medication, while diabetes management may include insulin or oral medications along with a controlled diet. "
            "Always consult your doctor before starting or changing any therapy."
            + DISCLAIMER
        )

    if "how to" in query_lower or "what can i do" in query_lower or "should i" in query_lower or "can i" in query_lower:
        return (
            "I can help explain your test results and suggest general lifestyle advice, such as healthier eating, regular physical activity, and stress management. "
            "If you want a more specific plan, ask me about the particular lab test or condition that concerns you."
            + DISCLAIMER
        )

    return (
        "I can answer questions about medical test terms, conditions, symptoms, diet, exercise, and health score meaning. "
        "Please ask a clear question like 'What is HbA1c?', 'What does high LDL mean?', or 'How can I lower my blood pressure?'."
        + DISCLAIMER
    )


def process_chat_query(query, biomarkers=None, user_profile=None):
    """
    Processes a chat query about medical terms, lab results, and recommendations.
    Uses current report biomarkers and user profile for context.
    Calls local Ollama instance (llama3:latest) if active, falling back to local glossary rules.
    """
    query_lower = query.lower()
    
    # Try using local Ollama model
    try:
        import urllib.request
        import json
        
        # System prompt with context integration
        system_prompt = (
            "You are AURA MED, an advanced clinical AI Medical Assistant. "
            "Your task is to answer the patient's questions about their medical parameters, lab results, healthy ranges, and dietary/exercise lifestyle recommendations. "
            "Be clinical, professional, supportive, and clear. Use structured Markdown (bullet points, bold text, headers) for readability.\n\n"
        )
        
        context = ""
        if user_profile:
            context += "Patient Profile:\n"
            context += f"- Age: {user_profile.get('age')} years\n"
            context += f"- Gender: {user_profile.get('gender')}\n"
            context += f"- BMI: {user_profile.get('bmi')} (Normal: 18.5 - 24.9)\n"
            context += f"- Smoking: {'Yes' if user_profile.get('smoking') else 'No'}\n"
            context += f"- Regular Exercise: {'Yes' if user_profile.get('exercise') else 'No'}\n"
            context += f"- Family Diabetes History: {'Yes' if user_profile.get('family_history_diabetes') else 'No'}\n"
            context += f"- Family Cardiovascular History: {'Yes' if user_profile.get('family_history_heart') else 'No'}\n\n"
            
        if biomarkers:
            context += "Latest Uploaded Report Biomarkers:\n"
            for b in biomarkers:
                context += f"- {b.get('name')}: {b.get('value')} {b.get('unit')} (Status: {b.get('status')}, Reference: {b.get('reference_range')})\n"
            context += "\n"

        prompt = f"{system_prompt}{context}Patient Question: {query}\n\nAI Response:"
        
        url = "http://localhost:11434/api/generate"
        data = {
            "model": "llama3:latest",
            "prompt": prompt,
            "stream": False
        }
        
        req = urllib.request.Request(
            url,
            data=json.dumps(data).encode('utf-8'),
            headers={'Content-Type': 'application/json'}
        )
        
        with urllib.request.urlopen(req, timeout=120) as response:
            res_data = json.loads(response.read().decode('utf-8'))
            ollama_response = res_data.get("response", "").strip()
            if ollama_response:
                return ollama_response + DISCLAIMER
    except Exception as e:
        print("Ollama connection failed or timed out. Falling back to local diagnostic rules. Error:", e)

    # Fallback to local glossary rules if Ollama fails or is not running
    if biomarkers and ("my results" in query_lower or "my report" in query_lower or "abnormal" in query_lower or "wrong" in query_lower):
        abnormalities = [b for b in biomarkers if b["status"] in ["High", "Low", "Borderline"]]
        if not abnormalities:
            response = "I've reviewed your latest medical report, and all extracted health biomarkers look **Normal**! Keep up the excellent work with your healthy habits. Is there a specific parameter you would like me to explain?"
        else:
            response = "Based on your latest medical report, here are the parameters that are out of the optimal reference ranges:\n\n"
            for b in abnormalities:
                status_color = "🔴 High" if b["status"] == "High" else "🔵 Low" if b["status"] == "Low" else "🟡 Borderline"
                response += f"- **{b['name']}**: {b['value']} {b['unit']} ({status_color}, range: {b['reference_range']})\n  *What it means*: {b['description']}\n\n"
            response += "I recommend checking the **Recommendations** tab for tailored dietary and lifestyle modifications. Would you like me to explain any of these parameters in more detail?"
        return response + DISCLAIMER

    # 2. Check for matching glossary terms
    matched_terms = _find_glossary_matches(query_lower)
    if matched_terms:
        matched_term = matched_terms[0]
        glossary_info = MEDICAL_GLOSSARY[matched_term]
        report_context = _get_report_context(matched_term, biomarkers)
        response = f"### {glossary_info['full_name']}\n\n{glossary_info['explanation']}{report_context}\n\n**What you can do:**\n{glossary_info['actions']}"
        return response + DISCLAIMER

    # 3. Check if asking about diet, exercise, or health scores
    if "diet" in query_lower or "food" in query_lower or "eat" in query_lower:
        if biomarkers:
            abnormalities = [b for b in biomarkers if b["status"] in ["High", "Low", "Borderline"]]
            if abnormalities:
                response = "Since you have some out-of-range parameters (such as " + ", ".join([b['name'] for b in abnormalities]) + "), your diet should focus on managing these. I suggest:\n\n"
                # Give high-level summary
                diet_tips = []
                for b in abnormalities:
                    if b['name'] in ["Fasting Glucose", "Postprandial Glucose", "HbA1c"]:
                        diet_tips.append("- Reduce simple sugars, refined carbs, and sweets. Increase whole grains and lean proteins.")
                    elif b['name'] in ["Hemoglobin", "RBC"]:
                        diet_tips.append("- Consume iron-rich foods (spinach, red meat, beans) paired with vitamin C (citrus fruits).")
                    elif b['name'] in ["Total Cholesterol", "LDL Cholesterol", "Triglycerides"]:
                        diet_tips.append("- Lower saturated and trans fats. Increase soluble fiber (oats) and healthy omega-3 fats.")
                    elif b['name'] in ["Systolic BP", "Diastolic BP"]:
                        diet_tips.append("- Reduce sodium (salt) intake, adopt a DASH diet (fruits, vegetables, low-fat dairy).")
                response += "\n".join(set(diet_tips)) + "\n\nYou can view your fully customized, detailed dietary roadmap in the **Recommendations** tab!"
                return response + DISCLAIMER
        response = "For general wellness, focus on a balanced diet incorporating:\n- **Lean Proteins**: Chicken, fish, eggs, tofu, and legumes.\n- **Complex Carbohydrates**: Oats, brown rice, quinoa, and vegetables.\n- **Healthy Fats**: Avocados, nuts, seeds, and extra virgin olive oil.\n- **Hydration**: Drink 2.5 - 3 liters of water daily and limit sugary beverages."
        return response + DISCLAIMER

    if "exercise" in query_lower or "workout" in query_lower or "gym" in query_lower or "activity" in query_lower:
        response = "A balanced physical activity routine should include:\n- **Cardio**: 150 minutes of moderate-intensity activity (e.g. brisk walking, cycling, swimming) per week.\n- **Strength**: 2-3 resistance training sessions per week to build muscle and increase metabolism.\n- **Flexibility**: Daily stretching or yoga to maintain joint mobility.\n\n*Note: If your report indicates extremely low Hemoglobin levels (<10 g/dL) or severe hypertension, avoid heavy weight lifting or highly strenuous workouts, and consult your physician before starting an exercise regimen.*"
        return response + DISCLAIMER

    if "health score" in query_lower or "score" in query_lower:
        if biomarkers:
            score = calculate_health_score(biomarkers)
            rating = "Excellent" if score >= 90 else "Good" if score >= 75 else "Moderate" if score >= 60 else "Attention Required"
            response = f"Your current Health Score is **{score}/100** ({rating}).\n\nThis score is computed by starting at 100 and deducting points based on the number and severity of biomarkers that fall outside the healthy clinical reference range. To raise your score, review the **Recommendations** tab and focus on correcting your borderline and critical parameters."
            return response + DISCLAIMER
        response = "Your Health Score is a visual rating from 30 to 100 based on the results of your uploaded medical reports. A score of 90+ is Excellent, 75-89 is Good, 60-74 is Fair, and below 60 means several biomarkers require attention. Upload a medical report in the **Dashboard** tab to calculate your score!"
        return response + DISCLAIMER

    # 4. Check if asking about a condition or broader medical topic
    condition_response = _build_condition_response(query_lower, biomarkers, user_profile)
    if condition_response:
        return condition_response

    # 5. If this is a general medical question, return a helpful explanation
    if _is_general_medical_query(query_lower):
        return _build_general_response(query_lower, biomarkers)

    # 6. Default conversational response
    if "diet" in query_lower or "food" in query_lower or "eat" in query_lower:
        if biomarkers:
            abnormalities = [b for b in biomarkers if b["status"] in ["High", "Low", "Borderline"]]
            if abnormalities:
                response = "Since you have some out-of-range parameters (such as " + ", ".join([b['name'] for b in abnormalities]) + "), your diet should focus on managing these. I suggest:\n\n"
                # Give high-level summary
                diet_tips = []
                for b in abnormalities:
                    if b['name'] in ["Fasting Glucose", "Postprandial Glucose", "HbA1c"]:
                        diet_tips.append("- Reduce simple sugars, refined carbs, and sweets. Increase whole grains and lean proteins.")
                    elif b['name'] in ["Hemoglobin", "RBC"]:
                        diet_tips.append("- Consume iron-rich foods (spinach, red meat, beans) paired with vitamin C (citrus fruits).")
                    elif b['name'] in ["Total Cholesterol", "LDL Cholesterol", "Triglycerides"]:
                        diet_tips.append("- Lower saturated and trans fats. Increase soluble fiber (oats) and healthy omega-3 fats.")
                    elif b['name'] in ["Systolic BP", "Diastolic BP"]:
                        diet_tips.append("- Reduce sodium (salt) intake, adopt a DASH diet (fruits, vegetables, low-fat dairy).")
                response += "\n".join(set(diet_tips)) + "\n\nYou can view your fully customized, detailed dietary roadmap in the **Recommendations** tab!"
                return response + DISCLAIMER
        
        response = "For general wellness, focus on a balanced diet incorporating:\n- **Lean Proteins**: Chicken, fish, eggs, tofu, and legumes.\n- **Complex Carbohydrates**: Oats, brown rice, quinoa, and vegetables.\n- **Healthy Fats**: Avocados, nuts, seeds, and extra virgin olive oil.\n- **Hydration**: Drink 2.5 - 3 liters of water daily and limit sugary beverages."
        return response + DISCLAIMER

    if "exercise" in query_lower or "workout" in query_lower or "gym" in query_lower or "activity" in query_lower:
        response = "A balanced physical activity routine should include:\n- **Cardio**: 150 minutes of moderate-intensity activity (e.g. brisk walking, cycling, swimming) per week.\n- **Strength**: 2-3 resistance training sessions per week to build muscle and increase metabolism.\n- **Flexibility**: Daily stretching or yoga to maintain joint mobility.\n\n*Note: If your report indicates extremely low Hemoglobin levels (<10 g/dL) or severe hypertension, avoid heavy weight lifting or highly strenuous workouts, and consult your physician before starting an exercise regimen.*"
        return response + DISCLAIMER

    if "health score" in query_lower or "score" in query_lower:
        if biomarkers:
            score = calculate_health_score(biomarkers)
            rating = "Excellent" if score >= 90 else "Good" if score >= 75 else "Moderate" if score >= 60 else "Attention Required"
            response = f"Your current Health Score is **{score}/100** ({rating}).\n\nThis score is computed by starting at 100 and deducting points based on the number and severity of biomarkers that fall outside the healthy clinical reference range. To raise your score, review the **Recommendations** tab and focus on correcting your borderline and critical parameters."
            return response + DISCLAIMER
        response = "Your Health Score is a visual rating from 30 to 100 based on the results of your uploaded medical reports. A score of 90+ is Excellent, 75-89 is Good, 60-74 is Fair, and below 60 means several biomarkers require attention. Upload a medical report in the **Dashboard** tab to calculate your score!"
        return response + DISCLAIMER

    # 4. Default conversational response
    response = (
        "Hello! I am your AI Medical Report Assistant.\n\n"
        "You can ask me questions like:\n"
        "- *'What is HbA1c?'* or *'Explain LDL Cholesterol'* (to understand medical terms)\n"
        "- *'Check my results'* (to summarize your uploaded report's abnormalities)\n"
        "- *'What diet should I follow?'* or *'How can I lower my blood sugar?'* (for lifestyle advice)\n\n"
        "How can I help you understand your health parameters today?"
    )
    return response + DISCLAIMER
